import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componets/Navbar";
import Footer from "./componets/footer";
import { getServerSession } from "next-auth";
import AuthProvider from "./lib/SessionProvider";
import Providers from "./redux/provider";
// import { SessionProvider } from "./lib/SessionProvider";
// import SessionProvider from "@/utils/SessionProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log("on serve from layout", session);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers> */}
          <AuthProvider session={session}>{children}</AuthProvider>
        {/* </Providers> */}
      </body>
    </html>
  );
}
